stages:
  - deploy

variables:
  PROJECT_FILE: Luizio.ServiceProxy/Luizio.ServiceProxy.csproj
  NUGET_API_KEY: oy2ltkpdmvxcpuvx4arakdjqizlssftuvkeixtlit3kzza

deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:9.0 # Use the .NET SDK image
  script:
    - dotnet restore $PROJECT_FILE
    - dotnet build -c Release --no-restore $PROJECT_FILE
    - dotnet pack -c Release --no-build $PROJECT_FILE
    - dotnet nuget push --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json Luizio.ServiceProxy/**/*.nupkg
  rules:
    - when: manual # Matches 'workflow_dispatch' from GitHub Actions